command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_GENIE_SPACE_ID
    valueFrom: genie-space
  - name: GENIE_KNOWLEDGE_STORE_PATH
    value: catalog_schemas_description/genie_knowledge_store.json
  - name: AGGRID_LICENSE_KEY
    valueFrom: aggrid-license-key